name: Validate manifest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund
      - name: Run manifest validator
        run: |
          npm run validate:manifest

  validate-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        shell: pwsh
        run: |
          # Install Pester for the current user (non-admin)
          Install-Module -Name Pester -Scope CurrentUser -Force -SkipPublisherCheck
      - name: Run Pester test for install-node dry-run
        shell: pwsh
        run: |
          pwsh -NoProfile -Command "Import-Module Pester; Invoke-Pester -Script './scripts/tests/test-install-node-dryrun.Tests.ps1' -EnableExit"